# Generated by Django 5.0.6 on 2024-05-19 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='item_type',
            field=models.CharField(choices=[('P', 'PHYSICAL'), ('v', 'VIRTUAL')], default='P', max_length=1),
        ),
        migrations.CreateModel(
            name='BasketModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('products', models.ManyToManyField(blank=True, default=None, to='products.productmodel')),
            ],
        ),
    ]
